### ISSUE TITLE
Baysor: Method writeup?

### ISSUE THREAD

**Issue by sandhya212** [kharchenkolab/Baysor#1]
Hi Victor, 

This is very interesting work. Do you have details of your method written down that you could please share?
Thanks indeed. 

Regards,
Sandhya

**Comment by VPetukhov** [comment]
Hi Sandhya,
We're still working on the development and didn't start write-up yet. Hopefully will have some version till the summer end, but no guaranties. The only existing description at the moment is the [presentation](https://docs.google.com/presentation/d/19r9yftEGmOUjC4IgE6JprcWdbr2PNDtM70qrO-w33mc) we gave some time ago fro SpaceTx consortium. But it's kind of out of date, and hard to understand without explanations. Anyway, I would be happy to answer your questions if you have some specific interests.

**Comment by sandhya212** [comment]
Thank you Victor for the quick response. And for sharing the deck. 
> Do I understand correctly, that a) you dock a 'cell center' at the DAPI-defined centroid and b) use scRNAseq data to cluster genes (or cells?) so that you get gene-gene coexpression matrices which you can then use to c) identify spatially where these coexpression neighbourhoods occur around a 'cell centre' to delineate then into 'cells'. 
> I did not quite get the role of k-means to identify neighbours. 
> How many iterations of EM would you need for the example you have in your presentation.
This is real interesting work so asking out of curiosity, but if this sensitive and you do not want to discuss here, am more than happy to wait for your write-up.

**Comment by VPetukhov** [comment]
Hi Sandhya,
As we're not exactly at the stage of write-up yet, I added [the links](https://github.com/hms-dbmi/Baysor#method-description) to my poster and mini-presentation on Baysor to the readme. Could be interesting for you.

**Comment by sandhya212** [comment]
Thank you Victor for sharing the updates 👍

**Comment by VPetukhov** [comment]
Alright, [the pre-print](https://doi.org/10.1101/2020.10.05.326777) is finally there! Please, feel free to ask any further questions on the method.
