### ISSUE TITLE
Export segmentation polygons as .geojson or tiff

### ISSUE THREAD

**Issue by BioinfoTongLI** [kharchenkolab/Baysor#10]
Hello!

Thx for sharing such a nice job!

Just wondering if there's way to export cell border coordinates to a .geojson file (to load it in other tools) for visualization?

Many thx!

Best,
Tong

**Comment by VPetukhov** [comment]
Hello! In the next version I'm going to add an option for saving polygons as a tiff segmentation mask. Would it be enough for you, or is it critical to have geojson?

**Comment by BioinfoTongLI** [comment]
Hello! Thx for your fast reply. Tiff file will work too.
Looking forward to the next version then.
Best,
Tong

**Comment by VPetukhov** [comment]
Cool. Let's keep it open till I publish the changes.

**Comment by VPetukhov** [comment]
Hi Tong,
I realized that saving data to tiff is only possible when molecule coordinates are provided in pixel units. So to support the whole set of usecases I added GeoJSON (https://github.com/kharchenkolab/Baysor/commit/d7838b48a11fc83b45dbe1490381694acc1079eb). It's in the develop branch so far, but I'll release it some time this month. No tiff so far, though.

To use it, you need to provide `--save-polygons=GeoJSON` together with `-p`.

**Comment by rocketeer1998** [comment]
I'm still interested in how to view the geojson file in R. And I've read my geojson file into R using `FROM_GeoJson` function in `geojsonR` package. Any ideas?
