### ISSUE TITLE
`boundary_polygons` not defined. Baysor v0.6.2

### ISSUE THREAD

**Issue by tsvvas** [kharchenkolab/Baysor#102]
Hello Baysor team,

I tried to run Baysor in jupyter notebook, however the function `bound_polygons` mentioned elsewhere produced an error – not defined. Also I noticed that this function as well as many others is not exported anymore ([the whole block is commented](https://github.com/kharchenkolab/Baysor/blob/da5ffd3b1e9581b2695d8c91af1c067d08e0ac96/src/Baysor.jl#L9)). 

How should I run Baysor in interactive sessions?

Best regards,
Vasily

**Comment by Pedro-Pei** [comment]
Hi, have you solved the problem? I have the same problem with you.

**Comment by tsvvas** [comment]
Hi @Pedro-Pei! Sadly no, I couldn't figure out how to use the package beyond CLI.

**Comment by Pedro-Pei** [comment]
Hello Vasily, I download v0.5.2. And I find it works. I hope it is helpful to you.
