### ISSUE TITLE
Baysor produces invalid polygons

### ISSUE THREAD

**Issue by pakiessling** [kharchenkolab/Baysor#103]
Hi there,

I am working on creating a converter from Baysor output and I notice that a small percentage of Baysor .geojson output contains less than 4 coordinates and is therefore invalid. Any idea why this is happening?

Sample:

```
{'coordinates': [[[1274.0061070224892, 234.94768491936884],
   [1274.0061070224892, 234.94768491936884]]],
 'type': 'Polygon',
 'cell': 3105}
```

In my small dataset this happened to 78 out of 3565 cells

Baysor 0.6.2

**Comment by VPetukhov** [comment]
This is fixed in v0.7.0. Please, see the [changelog](https://github.com/kharchenkolab/Baysor/blob/master/CHANGELOG.md) for more details.
