### ISSUE TITLE
add more channel

### ISSUE THREAD

**Issue by andynkili** [kharchenkolab/Baysor#108]
Dear Baysor developers,

Is there a way/option to include multiple channels (not just the DAPI)?

Best,
Andy

**Comment by VPetukhov** [comment]
Dear @andynkili ,

Currently Baysor only accepts segmentation mask as input. This segmentation could be done based on multiple stains. Could you please expand on what use case you want to cover with multiple stains? Maybe we could add it in the pipeline.
