### ISSUE TITLE
Providing cell segmentation as a cell label column

### ISSUE THREAD

**Issue by kernco** [kharchenkolab/Baysor#11]
If I'm using a cell label column in the molecules table to give Baysor information about a prior segmentation, how would I indicate molecules that don't belong to any cell? Is this supported? I have a prior nuclei segmentation, but because it only includes nuclei there are many molecules outside the nuclei that aren't assigned to cells.

**Comment by VPetukhov** [comment]
Yes, this is supported and works exactly in the same way as a segmentation mask: you set the labels of non-assigned molecules to 0. It will not force them to be background (indeed, there is no such option currently), but will set them as unlabeled.
