### ISSUE TITLE
Not producing loom file output

### ISSUE THREAD

**Issue by dr-sayyadhury** [kharchenkolab/Baysor#110]
Hi, I am wondering why my command is not producing a loom output for an ncv run. Instead its giving me a .csv file instead.

I am running the command line on python. Here is my code.

Code
-----------
out_path1 = '/dir_path/out/segmentation/baysor/Control_1A_0005511/baysor_segmented'
out_path2 = '/dir_path/out/segmentation/baysor/Control_1A_0005511/ncv'

for path, dir, files in os.walk('/dir_path/out/segmentation/baysor/Control_1A_0005511/fov_segments'):
    for file in files:
        print(file)
        command = [
        '/home/shamini/.julia/bin/baysor', 'run',
        '-c', '/dir_path/baysor_processing/baysor.toml',
        '-x', 'x_location',
        '-y', 'y_location',
        '-z', 'z_location',
        '-g', 'feature_name',
        '-s', '9',
        '--save-polygons', 'geojson',
        '--prior-segmentation-confidence', '0.5',
        '-o', os.path.join(out_path1, file),
        os.path.join(path,file)
        ]
        subprocess.run(command, check=True)

        command = [
        '/home/shamini/.julia/bin/baysor', 'segfree',
        '-c', '/dir_path/baysor_processing/baysor.toml',
        '-x', 'x_location',
        '-y', 'y_location',
        #'-z', 'z_location',
        '-g', 'feature_name',
        #'-s', '9',
        #'--save-polygons', 'geojson',
        #'--prior-segmentation-confidence', '0.5',
        '-o', os.path.join(out_path2, file),
        os.path.join(path,file)
        ]
        subprocess.run(command, check=True)

**Comment by VPetukhov** [comment]
That's odd. If it's still relevant, could you please provide a log file?
