### ISSUE TITLE
Running 3D Segmentation

### ISSUE THREAD

**Issue by NickDiNapoli** [kharchenkolab/Baysor#111]
I am trying to obtain a 3D segmentation result from what I believe is the way to do so. I am not using `PRIOR_SEGMENTATION` in this run.

1. Specify `z` column name in the `MOLECULES_CSV` via `'-z'` parameter
2. Set `force_2d = false` in the `config.toml` file

The README documentation explains: 

**_segmentation_polygons.json_**: polygons used for visualization in GeoJSON format. In the case of 3D segmentation, it is an array of GeoJSON polygons per z-plane, as well as "joint" polygons. _Shown only if `--save-polygons=geojson` is set._

The output GeoJSON only contains one set of 2D geometries instead of the expected output above. Can you please advise what aspect I am missing to obtain a 3D output?

Run parameters:
~/.julia/bin/baysor run \
    'transcripts.csv' \
    -c 'example_config_3d.toml' \
    -x 'global_x' -y 'global_y' -z 'global_z' -g 'gene' -m 20 -s 5 \
    --save-polygons=geojson \
    -p \
    -o 'test'

Environment is:
NAME="Amazon Linux AMI"
VERSION="2018.03"

**Comment by NickDiNapoli** [comment]
@FalkoHof Thanks so much for linking your issue. It seems like your run got to the point where 3D segmentation was at least recognized. Out of curiosity, what did you do differently to at least get to that point, even if your run ultimately errored out because of the too many z values issue?

**Comment by FalkoHof** [comment]
The 3D segmentation was working for me irrespectively of using floats or ints on the z-axis. What kind of data are you using as input?  I used Xenium data and followed this [workflow ](https://www.10xgenomics.com/analysis-guides/using-baysor-to-perform-xenium-cell-segmentation) (but deviated a bit from it due to changes in baysor and the xenium output).

What is the error baysor is throwing in your case?

**Comment by VPetukhov** [comment]
Apologies for the late reply. This is a bug with polygon outputs. The segmentation is still done in 3D, but the polygons are not estimated properly. It will be fixed in the next release.

**Comment by VPetukhov** [comment]
This is fixed in v0.7.0. Please, see the [changelog](https://github.com/kharchenkolab/Baysor/blob/master/CHANGELOG.md) for more details.
