### ISSUE TITLE
Error with downloading artifact of JpegTurbo; tree hash mismatch

### ISSUE THREAD

**Issue by gretajuu** [kharchenkolab/Baysor#112]
Hello,

I have been trying to install Baysor to function with Julia with several different versions of Julia without success.  I end up with the same error code. My latest try is with Julia 1.9.4 according to your README file and I got this error below. My experience with Julia is very limited so apologies if I have traced the problem to the wrong source. However, I have also tried to use Baysor-master files though usage of /build.jl-file and it failed too. Could it be that there is some miscommunication problem with Baysor and Julia?
````
ERROR: Unable to automatically download/install artifact 'JpegTurbo' from sources listed in '~/.julia/packages/JpegTurbo_jll/eZeua/Artifacts.toml'.
Sources attempted:
- https://pkg.julialang.org/artifact/29140655412cfb436ef0a394900bec45913cb372
    Error: Tree Hash Mismatch!
  Expected git-tree-sha1:   29140655412cfb436ef0a394900bec45913cb372
  Calculated git-tree-sha1: e2cf3c44b2b2fa68dcf8e6bdd53a3eb8b17e27ee
- https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.2+0/JpegTurbo.v3.0.2.x86_64-linux-gnu.tar.gz
    Error: Tree Hash Mismatch!
  Expected git-tree-sha1:   29140655412cfb436ef0a394900bec45913cb372
  Calculated git-tree-sha1: e2cf3c44b2b2fa68dcf8e6bdd53a3eb8b17e27ee

**Comment by VPetukhov** [comment]
That may happen if you have some exotic setup. If it's still relevant, could you please provide your system info, the commands you run and a full output log.
