### ISSUE TITLE
Loading binary image sementation mask as prior: MethodError: no method matching sparse

### ISSUE THREAD

**Issue by Sengels24** [kharchenkolab/Baysor#119]
Hi,

First of all, thanks for making Baysor, its amazing! Baysor works for me without prior segmentation, but when I add a binary image with a segmentation mask (Black background, cell segmentation = red) as a prior (in tif. format), I get the following error:

Info: Excluding genes: 
Info: Loaded 8329256 transcripts
Info: Loading segmentation mask...
ERROR: LoadError: MethodError: no method matching sparse(::MappedArrays.MappedArray{UInt8, 3, Base.ReinterpretArray{FixedPointNumbers.N0f8, 3, ColorTypes.RGBA{FixedPointNumbers.N0f8}, Matrix{ColorTypes.RGBA{FixedPointNumbers.N0f8}}, true}, typeof(reinterpret), ImageCore.var"#39#40"{FixedPointNumbers.N0f8}})

Closest candidates are:
  sparse(::Any, !Matched::Any, !Matched::Number, !Matched::Any, !Matched::Any, !Matched::Function)
   @ SparseArrays ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl:1322
  sparse(::Any, !Matched::Any, !Matched::AbstractVector{Bool}, !Matched::Any, !Matched::Any)
   @ SparseArrays ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl:1320
  sparse(::Any, !Matched::Any, !Matched::AbstractVector, !Matched::Any, !Matched::Any)
   @ SparseArrays ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl:1318`

It seems like there is no method matching sparse. Did u encounter this issue before?

Many thanks :)

**Comment by saito-k1** [comment]
I'm having the same issue when I add a tif file as my prior segmentation. Were you able to find a workaround?

**Comment by VPetukhov** [comment]
Apologies for the late reply. Only single-channel images are supported. Would the error persist if you flatten the image to a single binary channel?
