### ISSUE TITLE
The HTML file output by the baysor preview or baysor run command exceeds 1 GB, making it impossible to browse using a standard web browser.

### ISSUE THREAD

**Issue by MOSAIFENG** [kharchenkolab/Baysor#121]
I used the vpetukhov/baysor.6.2 Docker image of Baysor to re-segment Xenium data. The resulting HTML file exceeds 1 GB, which means it can only be viewed as text using the file editor EmEditor, and cannot be rendered by mainstream browsers.

**Comment by VPetukhov** [comment]
Yeah, showing whole data for the modern protocols with large tissues is problematic. You can try reducing [`min_pixels_per_cell`](https://github.com/kharchenkolab/Baysor/blob/eaa4b28f413bf55529c6d758210b5c280107878e/configs/example_config.toml#L32) in the config. But in general I'd suggest to omit plotting it in the report and doing some manual visualizations.

**Comment by VPetukhov** [comment]
The new version (0.7.0) should have it fixed. Please, see the [changelog](https://github.com/kharchenkolab/Baysor/blob/master/CHANGELOG.md) for more details.
