### ISSUE TITLE
Output matrix formatted wrong for tsv

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [kharchenkolab/Baysor#125]
I just ran Baysor v6.2.0 wit the flag ```--count-matrix-format tsv```. In my output however, the genes are listed as the columns, but the matrix columns exceed the number of gene names. The rows however match the number of gene names. I think either the matrix needs to be transposed or the gene names need to be put as rownames, not column names.
The cell names are also missing, so I can't really connect the information from the geojson polygons to the count matrix.

**Comment by VPetukhov** [comment]
Thank you for reporting it! That's definitely a bug.

**Comment by VPetukhov** [comment]
This is fixed in v0.7.0. Please, see the [changelog](https://github.com/kharchenkolab/Baysor/blob/master/CHANGELOG.md) for more details.
