### ISSUE TITLE
Installation Issue as Julia Package

### ISSUE THREAD

**Issue by marsdenl** [kharchenkolab/Baysor#135]
Hi there, 

I've been trying to install Baysor to run segmentation via SOPA on a MERSCOPE dataset. Using the Julia package installation method on a VM windows desktop, the installation has been paused it seems (or has been running for quite some time > 60mn). I have GCC and Julia installed and my code for the installation is: 
julia -e "using Pkg; Pkg.add(PackageSpec(url=\"https://github.com/kharchenkolab/Baysor.git\")); Pkg.build()"

The pausing occurs at:
 Resolving package versions...
  No Changes to `C:\Users\user\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\user\.julia\environments\v1.10\Manifest.toml`
Precompiling project...
  309 dependencies successfully precompiled in 198 seconds. 9 already precompiled.
  1 dependency had output during precompilation:
┌ Formatting
│  ┌ Warning: DEPRECATION NOTICE
│  │
│  │ Formatting.jl has been unmaintained for a while, with some serious
│  │ correctness bugs compromising the original purpose of the package. As a result,
│  │ it has been deprecated - consider using an alternative, such as
│  │ `Format.jl` (https://github.com/JuliaString/Format.jl) or the `Printf` stdlib directly.
│  │
│  │ If you are not using Formatting.jl as a direct dependency, please consider
│  │ opening an issue on any packages you are using that do use it as a dependency.
│  │ From Julia 1.9 onwards, you can query `]why Formatting` to figure out which
│  │ package originally brings it in as a dependency.
│  └ @ Formatting C:\Users\user\.julia\packages\Formatting\3VxOt\src\Formatting.jl:12
└
    Building HDF5 ──→ `C:\Users\user\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\114e20044677badbc631ee6fdc80a67920561a29\build.log`
    Building Baysor → `C:\Users\user\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\69139e6b79413cf8d068d520ebc69f987e633c98\build.log`
  Progress [====================>                    ]  1/2

Do you know why that might be the case? Any help would be greatly appreciated thank you. 

Luc

**Comment by VPetukhov** [comment]
Hi Luc, on my laptop it may take ~30 minute single-thread, as the process compiles a lot of packages. You can parallelize it using `JULIA_NUM_THREADS=13 julia -e "using Pkg; Pkg.add(PackageSpec(url="[https://github.com/kharchenkolab/Baysor.git\](https://github.com/kharchenkolab/Baysor.git%5C)")); Pkg.build()"`. I will add this to the readme.

Please, let me know if this doesn't work!

**Comment by marsdenl** [comment]
It worked, in the end, thanks for your help @VPetukhov :)
