### ISSUE TITLE
Inconsistency between the number of non-null cells from segmentation.csv and cell ids from segmentation_polygons_2d.json

### ISSUE THREAD

**Issue by HarryZhang1224** [kharchenkolab/Baysor#141]
Dear Baysor team,

Thanks for the amazing tool! I ran the newest version of Baysor and input the results to Xenium Ranger v3.0.1. It reports an error where some cells in segmentation.csv file's "cell" column are not saved in the segmentation_polygons_2d.json file. Specifically, the unique cells from these two files are not identical. Do you have an idea of what might be happening?

Thanks,
Harry

**Comment by VPetukhov** [comment]
Hi @HarryZhang1224 ,

The `cell` column includes all cells regardless of their size. Polygons are filtered, so cells have at least 3 molecules (GeoJSON requirement).
