### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by YubinXie** [kharchenkolab/Baysor#16]
Hi I am trying to run Baysor on the given examples ISS and got the following error:

I downloaded the binary source and was directly calling baysor in the bin.

```
bash-4.2$ ~/tool/Baysor/bin/baysor -i 500 -n 20 -p -c ~/tool/Baysor/iss.toml -o ./output_dapi -p ./data/pciSeq_3-3.csv ./data/DAPI_3-3_mask.tif
┌ Error: Can't parse argument -i
└ @ Baysor /home/vpetukhov/.julia/dev/Baysor/src/cli/common.jl:125
Usage: baysor <command> [options]

Commands:
        run             run segmentation of the dataset
        preview         generate preview diagnostics of the dataset

```

**Comment by VPetukhov** [comment]
Yeah, those are out of date, and I'm yet to fix it. Indeed, it's [written in the README](https://github.com/kharchenkolab/Baysor#normal-run). Here it should be `baysor run -i 500 ...`.
