### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by jnmark** [kharchenkolab/Baysor#21]
Hello,

I got this out of memory error in processing a few times which prevents the creation of the output .csv file. Initially I noticed this happening when the ```-m``` value was small in which case there were many cells, but a few times, I have seen it happen for larger  ```-m``` values as well. I am doing a comparison test, so I do need to run Baysor with different parameters. The parameters and log is below:

Run parameters:
```./baysor run -p -x X -y Y --prior-segmentation-confidence 0.8 -m 75 -o /Users/jnmark/DAPI_prior_c0_8.csv /Users/jnmark/Reads/reads.csv /Users/jnmark/DAPI/DAPI_proc.tif```

Log output:
```
┌ Warning: No config file provided. Using default parameters.
└ @ Baysor /home/vpetukhov/.julia/dev/Baysor/src/cli/main.jl:91
[08:52:38] Info: (2021-11-03) Run Baysor v0.5.0
[08:52:38] Info: Loading data...
[08:52:52] Info: Loaded 1882562 transcripts
[08:52:52] Info: Loading segmentation mask...
[08:54:27] Info: Done
[08:54:27] Info: Estimating prior segmentation polygons...
[09:41:06] Info: Done
[09:41:07] Info: Estimating noise level
[09:42:50] Info: Done
[09:44:00] Info: Clustering molecules...
Progress: 100%|█████████████████████████████████████████| Time: 0:07:18
  Iteration:                  407
  Max. difference:            0.008663200982013564
  Fraction of probs changed:  0.4727828353063538
[09:52:44] Info: Algorithm stopped after 407 iterations. Error: 0.00866. Converged: true.
[09:52:45] Info: Done
[09:52:46] Info: Initializing algorithm. Scale: 145.626501218387, scale std: 12.348453881948412, initial #components: 50200, #molecules: 1882562.
[09:52:57] Info: Using 2D coordinates
Progress: 100%|█████████████████████████████████████████| Time: 0:57:39
  Iteration:        500
  Noise level, %:   2.36
  Num. components:  4974
[10:51:31] Info: Processing complete.
[10:52:16] Info: Estimating local colors
[10:52:51] Error: OutOfMemoryError()
|                 
|                 Array at boot.jl:450 [inlined]
|                 Array at boot.jl:458 [inlined]
|                 Array at boot.jl:465 [inlined]
|                 similar at abstractarray.jl:785 [inlined]
|                 similar at abstractarray.jl:784 [inlined]
|                 similar at broadcast.jl:197 [inlined]
|                 similar at broadcast.jl:196 [inlined]
|                 copy at broadcast.jl:908 [inlined]
|                 materialize at broadcast.jl:883 [inlined]
|                 covm(x::Matrix{Float64}, xmean::Vector{Float64}, vardim::Int64; corrected::Bool) at Statistics.jl:545
|                 covm at Statistics.jl:545 [inlined]
|                 fit(::Type{MultivariateStats.PCA}, X::Matrix{Float64}; method::Symbol, maxoutdim::Int64, pratio::Float64, mean::Nothing) at pca.jl:152
|                 fit at pca.jl:138 [inlined]
|                 gene_composition_transformation(count_matrix::Matrix{Float64}, confidence::Vector{Float64}; sample_size::Int64, seed::Int64, method::Symbol, return_all::Bool, n_pcs::Int64, out_dim::Int64, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}) at neighborhood_composition.jl:68
|                 gene_composition_transformation at neighborhood_composition.jl:60 [inlined]
|                 gene_composition_colors(df_spatial::DataFrames.DataFrame, k::Int64; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}) at neighborhood_composition.jl:123
|                 gene_composition_colors at neighborhood_composition.jl:121 [inlined]
|                 save_segmentation_results(bm_data::Baysor.BmmData{2}, gene_names::Vector{String}, args::Dict{String, Any}; mol_clusts::NamedTuple{(:exprs, :assignment, :diffs, :assignment_probs, :change_fracs), Tuple{Matrix{Float64}, Vector{Int64}, Vector{Float64}, Matrix{Float64}, Vector{Float64}}}, comp_segs::Nothing, prior_polygons::Vector{Matrix{Float64}}) at main.jl:393
|                 (::Baysor.var"#save_segmentation_results##kw")(::NamedTuple{(:mol_clusts, :comp_segs, :prior_polygons), Tuple{NamedTuple{(:exprs, :assignment, :diffs, :assignment_probs, :change_fracs), Tuple{Matrix{Float64}, Vector{Int64}, Vector{Float64}, Matrix{Float64}, Vector{Float64}}}, Nothing, Vector{Matrix{Float64}}}}, ::typeof(Baysor.save_segmentation_results), bm_data::Baysor.BmmData{2}, gene_names::Vector{String}, args::Dict{String, Any}) at main.jl:389
|                 run_cli_main(args::Vector{String}) at main.jl:470
|                 run_cli(args::Vector{String}) at common.jl:118
|                 run_cli at common.jl:103 [inlined]
|                 julia_main at common.jl:139 [inlined]
|                 julia_main() at none:36
└ Baysor /home/vpetukhov/.julia/dev/Baysor/src/cli/common.jl:132
```

Thanks for the help!

**Comment by VPetukhov** [comment]
Hi @jnmark ,
Based on the log it's happening when estimating neighborhood composition colors, which requires constructing a matrix of 'num. molecules' x 'num. genes' size. How many genes do you have in the dataset? And how much memory do you have?

**Comment by jnmark** [comment]
Hi @VPetukhov, thanks for the response! I have ~1050k reads in the reads.csv file. And I am running Baysor on a high performance cluster, I reserved 50G prior to running Baysor, I will try that increasing that parameter. Would you be able to provide any guidance on when this error might occur and if I can take any steps to prevent it? I was mainly curious why it sometimes occurs for larger ```-m 75``` but not smaller values such as ```-m 5```, which would mean there are more cells.

**Comment by timwiggin** [comment]
Is it possible to skip the neighborhood color step? I'm having a similar problem, but the process is being killed by the OS once it consumes >150Gb of memory rather than throwing an error. Based on the expected matrix size, if you're using int64, color estimation will take ~200Gb of RAM for my dataset.

**Comment by VPetukhov** [comment]
> Is it possible to skip the neighborhood color step?

My bad, but currently it's not. I'm going to fix it during the next 1-2 weeks.

**Comment by VPetukhov** [comment]
@jnmark , @timwiggin , there is a [new release](https://github.com/kharchenkolab/Baysor/releases/tag/v0.5.1), which adds the option `--no-ncv-estimation`, can you please try if that works for you? And we're working on estimating NCVs using sparse matrices, which should be the final solution to the problem.

**Comment by arunchakra** [comment]
Hello, along these lines I would like to use the --no-ncv-estimation, but the assets for Version 0.5.1 do not contain a linux binary(only ubuntu which isn't working on my linux). Could you please release a linux specific binary?

**Comment by VPetukhov** [comment]
In the [v0.6.0](https://github.com/kharchenkolab/Baysor/releases/tag/v0.6.0) I switched to sparse PCA for NCV estimation on large datasets. So, the memory problem should be solved.

@arunchakra , the new linux binary should work on most x64 linux distributions, but I also [simplified the installation process](https://github.com/kharchenkolab/Baysor#install-as-a-julia-package), so that's now a recommended way in case binaries don't work on your system.
