### ISSUE TITLE
Error when try to install Baysor in Ubuntu

### ISSUE THREAD

**Issue by JB-Nette** [kharchenkolab/Baysor#34]
Hi, I am using Ubuntu on Window. I tried to install the Baysor using these following command line:
git clone https://github.com/kharchenkolab/Baysor.git
cd Baysor/bin
make

I got an error message which is
![image](https://user-images.githubusercontent.com/80437853/150069833-b3e0a257-3a33-46d4-8981-c127605db972.png)
ending with make: *** [Makefile:16: baysor] Error 1

Please help. Thank you.

**Comment by VPetukhov** [comment]
Hi, I need to look into it. But first of all, why don't you just use [the binaries](https://github.com/kharchenkolab/Baysor#binary-download)?

**Comment by JB-Nette** [comment]
Hi, I figure out that it is because my company's intranet block some ip address.
I tried binaries it works fine ! Thank you so much for your reply.
