### ISSUE TITLE
Issue with MacOS binaries

### ISSUE THREAD

**Issue by kleejin** [kharchenkolab/Baysor#36]
Hello, I am having trouble using the MacOS binaries, getting the following message. Any ideas?

./baysor --help
Two passes with the same argument (-LowerPTLS) attempted to be registered!
zsh: illegal hardware instruction  ./baysor --help

**Comment by VPetukhov** [comment]
Hi,
Can you please send your system details? Like OS version and hardware.

**Comment by kleejin** [comment]
OS info:
ProductName:	macOS
ProductVersion:	11.6.2
BuildVersion:	20G314

My machine is a macbook pro
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 32 GB 2667 MHz DDR4

**Comment by pander21** [comment]
Hi, I have the same issue on my Macbook Pro:
macOS Catalina 10.15.7
Processor: 2Ghz Quad-Core Intel Core i5
Memory: 16 Gb 3733 Mhz LPDDR4X

**Comment by munizmom** [comment]
I also have a MacOS Apple M1 Max, and made it work following 10x GENOMICS interactions : https://www.10xgenomics.com/jp/resources/analysis-guides/using-baysor-to-perform-xenium-cell-segmentation
Tools versions: python=3.9.12; julia-1.8.3  MacOS x86 no ARM version of Julia. Then installing 0.5.2 version of Baysor.

**Comment by VPetukhov** [comment]
Hi, please see the answer here: https://github.com/kharchenkolab/Baysor/issues/56 . I couldn't make reliable mac binaries, so please, install it as a Julia package.
