### ISSUE TITLE
Any idea about projecting cell type labels back to cell segmentation plot?

### ISSUE THREAD

**Issue by rocketeer1998** [kharchenkolab/Baysor#38]
Hi,  @VPetukhov. First of all, thanks for the convenience the `Baysor` has brought to my ISS study. After a full `baysor run`, I have obtained a beautiful cell segmentation plot and a useful expression matrix that I can use in the downstream scRNA-seq analysis. 

As for scRNA-seq analysis tool, I think `Seurat` is stabler and more robust than `pagoda2`, though the latter provides a convenient web app to analyze my data. So I want to perform a standard scRNA-seq pipeline using `Seurat` and label each cell with a cell type. So is there any recommendation about projecting this result back to the cell segmentation plot created by `Baysor`? Otherwise, I have to simulate a segmentation plot using ggplot2.

Thanks for your kind reply!

**Comment by VPetukhov** [comment]
Hi @rocketeer1998 , thanks for the feedback! 
Can you please specify, what exactly do you want to get as an output?

**Comment by rocketeer1998** [comment]
> Hi @rocketeer1998 , thanks for the feedback! Can you please specify, what exactly do you want to get as an output?

Just as shown in your publication Fig.6 e and f. I want to show the spatial distribution of some cell types based on marker gene expression. 

<img width="646" alt="Baysor" src="https://user-images.githubusercontent.com/55828283/160033225-34f9b51b-eef7-45f8-b804-d9cb78c18bdb.png">

**Comment by VPetukhov** [comment]
The annotation for that was done manually, and the plot just shows each cell as a dot, so we don't have the code for that in the package. To do the same, you can take cell positions from `segmentation_cell_stats.csv` and match it with `segmentation_counts.tsv` to get cell markers.

**Comment by rocketeer1998** [comment]
> The annotation for that was done manually, and the plot just shows each cell as a dot, so we don't have the code for that in the package. To do the same, you can take cell positions from `segmentation_cell_stats.csv` and match it with `segmentation_counts.tsv` to get cell markers.

OK. Thanks a lot!
