### ISSUE TITLE
A question about prior segmentation

### ISSUE THREAD

**Issue by rocketeer1998** [kharchenkolab/Baysor#39]
Hi @VPetukhov , I've got my cell segmentation plot after running `baysor run` with `[PRIOR_SEGMENTATION]` parameter and `prior-segmentation-confidence = 1` parameter. And my prior segmentation file is processed under your recommendation, which uses ImagJ to perform watershed segmentation. A part of my plot is like this:
<img width="611" alt="baysor" src="https://user-images.githubusercontent.com/55828283/161736076-4cd6cd3a-3737-47cc-8b72-be81d59ac7bf.png">
Does the yellow block correspond to DAPI nuclei? Or cell boundary? Why the cell boundary produced by `baysor run` is not totally covered by prior segmentation, even if I set `prior-segmentation-confidence = 1` ?

**Comment by tsuijenk** [comment]
Hi @rocketeer1998, sorry for interrupting here but maybe @VPetukhov can chip in as well. I got kind of confused by the output of Baysor. Baysor is supposed to do cell segmentation, if I am correct. But some of these cell areas here are so tiny that it includes one to two molecules. But biologically speaking, human cells have between 20,000 and 25,000 genes. Please advise! :)

**Comment by VPetukhov** [comment]
Hi everyone,
The details of the method are described in [the paper](https://www.nature.com/articles/s41587-021-01044-w), "Methods" -> "Cell segmentation" -> "Using a prior segmentation".

Regarding the points of @rocketeer1998 and @LucaGiudice : 
> The prior segmentation penalty is evaluated only for the molecules that are assigned to some cell (but not to background) in both Baysor and the prior segmentations. This accounts for the fact that the imaging-based segmentations may miss some cells or portions of cells that can still be deduced from the spatial transcriptomics data. The most obvious example of such situation are the DAPI-based segmentations, which cover only molecules within the cell nuclei, leaving most of the cytoplasm molecules unannotated.

@tsuijenk , Baysor can produce cells of arbitrary small sizes. And the estimate of 20k genes per cell does not help here, as it all comes down to the comes down to the capture rate and the number of measured genes. Protocols like [ISS](https://nilssonlab.org/research/in-situ-sequencing/), for example, can only have 1-2 molecules per cell. So, these small cells should be removed during post-processing, the same way you do cell size thresholding for scRNA-seq data.
