### ISSUE TITLE
Inconsistent cell number in the json file and cell stats file

### ISSUE THREAD

**Issue by zhanglab2008** [kharchenkolab/Baysor#41]
Hi @VPetukhov 
I wonder how to plot the cells (in polygon shapes) in the 2D tissue dimension after I finished clustering and cell type annotation. I saw that the zoom-in figure you showed in your Nature Biotech paper (figure3) is really amazing. I want to do the same with my own dataset.
I have successfully read the json file and make the plot but the cell number in the json file is inconsistent with that in the cell_stats file. Appreciated if you can help or give comments...
THanks!

**Comment by rocketeer1998** [comment]
> Hi @VPetukhov I wonder how to plot the cells (in polygon shapes) in the 2D tissue dimension after I finished clustering and cell type annotation. I saw that the zoom-in figure you showed in your Nature Biotech paper (figure3) is really amazing. I want to do the same with my own dataset. I have successfully read the json file and make the plot but the cell number in the json file is inconsistent with that in the cell_stats file. Appreciated if you can help or give comments... THanks!

Hi @zhanglab2008 , could you give me some recommendations about plotting the GeoJson file, which is produced by `save-polygons=geojson`?

**Comment by teng-gao** [comment]
I have the same question ..

**Comment by VPetukhov** [comment]
So, this is finally fixed in [v0.6.0](https://github.com/kharchenkolab/Baysor/releases/tag/v0.6.0)
