### ISSUE TITLE
Adjusting covariance 

### ISSUE THREAD

**Issue by ilyakorsunsky** [kharchenkolab/Baysor#45]
Hi, I am trying to reimplement this awesome method in R and ran into potential issues with computation of shrunken covariance: 

First, the var_posterior function seems to add the shrinkage adjustment to the prior mean rather than to the eigenvalue. This is different from the paper. Interestingly, it does kind of have the intended effect by shrinking the prior towards the eigenvalue, rather than the other way around. 

>     std_adj = (prior_std + sign(d_std) * (sqrt(abs(d_std) / prior_std_std + 1) - 1) * prior_std_std)

Second, when I implement the formulation from the paper, my shape estimates tend to diverge from the prior. I think this is because the formula reads `eigval + sign(eigval - prior) * ...`, which makes it so that we increase eigenvalues when eigenvalues exceed the prior and vice versa. I think this should be `eigval - sign(eigval - prior) * ...` to make the shrinkage move towards the prior. 

Would love to hear your thoughts and thank you for this wonderful contribution to the field! 

Best, 
Ilya

**Comment by VPetukhov** [comment]
Wow! That's pretty cool, and I'd be happy to help! Just in case, the slowest part of the method currently is [`fill_adjacent_component_weights!`](https://github.com/kharchenkolab/Baysor/blob/master/src/bmm_algorithm/bmm_algorithm.jl#L162), so it has to be done in C++. Though I'd go for the whole [`expect_dirichlet_spatial!`](https://github.com/kharchenkolab/Baysor/blob/master/src/bmm_algorithm/bmm_algorithm.jl#L153) to make it multi-threaded after converting `bmm_data.assignment` to `std::vector<std::atomic<size_t>>`.

> the var_posterior function seems to add the shrinkage adjustment to the prior mean rather than to the eigenvalue. This is different from the paper.

Oh, indeed. That's a mistake in the paper, not in the code. The intuition there is that we estimate deviation from the prior ([`d_std`](https://github.com/kharchenkolab/Baysor/blob/1d35964e894a4d974febe1b66f2f96daebca1b70/src/models/Component.jl#L21)), shrink it (`sign(d_std) * (sqrt(abs(d_std) / prior_std_std + 1) - 1) * prior_std_std`), and add it back to the prior.

**Comment by ilyakorsunsky** [comment]
Thanks for the explanation! That makes the code make sense more.
