### ISSUE TITLE
Updated Binary for Linux

### ISSUE THREAD

**Issue by arunchakra** [kharchenkolab/Baysor#47]
I would like to try --no-ncv-estimation option to prevent Out of Memory errors. However, the only binary for linux available does not have this option. Could you please provide an updated linux binary(not ubuntu specific)?

**Comment by VPetukhov** [comment]
@arunchakra , the provided binaries with name 'ubuntu' in them were compiled under ubuntu, but should be working for any Linux. Did you try them?

**Comment by bethrusnak** [comment]
Did this issue get solved? I have the same problem.

**Comment by vhaghani26** [comment]
I got this same GLIBC_2.29 error. It looks like it requires a minimum of Ubuntu version 19.04 to run. Upon upgrading, I got rid of that error; however, I ran into a new one.

**Comment by arunchakra** [comment]
Any updates on this? Again, it seems that the binary is still Ubuntu-specific currently and does not work on a linux cluster.

**Comment by leonardosepulveda** [comment]
I tried to run the last ubuntu Binary in a CentOS Linux 7 cluster (Harvard RC computing), and I got the same error described above.   Seems that this is a common problem with other software (https://github.com/darbyjohnston/DJV/issues/287).

**Comment by VPetukhov** [comment]
Hi everyone,
GLIBC_2.29 is pretty old now. The new compiled binary for v0.6.0 used GLIBC_2.31. It's hard to support all the old distributions, so I suggest [installing Baysor as a Julia package](https://github.com/kharchenkolab/Baysor#install-as-a-julia-package) in this case . I tried to simplify the procedure in v0.6.0.
