### ISSUE TITLE
No output when using 'color=:ncv_color' in plot_molecules

### ISSUE THREAD

**Issue by sebgoti** [kharchenkolab/Baysor#49]
New to Julia over here, so this might be an easy problem to fix, but I was following the notebook from the introductory video and was not able to plot the segmentation over cells and the polygons using ':ncv_color' as the value for 'color' in 'plot_molecules':

<img width="599" alt="image" src="https://user-images.githubusercontent.com/20914037/182207974-293ea10e-d69b-45ce-84d4-3f8615d8c229.png">

Though

<img width="523" alt="image" src="https://user-images.githubusercontent.com/20914037/182208258-ae396017-5f34-48e2-a94b-39fe23067012.png">

Any ideas of what is wrong?

**Comment by reillyeo** [comment]
Any solution to this? Am having the exact same issue

**Comment by VPetukhov** [comment]
This usually happens when some of the keyword arguments are incompatible with the plotting library. Could you please try a minimal version `B.plot_molecules(df_spatial, color=:ncv_color)`?

**Comment by VPetukhov** [comment]
Please, reopen if the issue persists
