### ISSUE TITLE
Example on Visium data

### ISSUE THREAD

**Issue by cartal** [kharchenkolab/Baysor#5]
Hi,

I'm very excited to see that Baysor is out. 

I'm trying to run it on a sample from 10X Visium data, and I was wondering if you can provide an example on 
how to achieve this using these files. 

Thanks!

**Comment by VPetukhov** [comment]
Hi,
Baysor is designed to perform cell segmentation on single-molecule data. So, the input is information about individual molecules. On the other hand, Visium measures expression in a 50-microne spot, which may have a couple of dozens of cells inside. So there is no way to perform segmentation there.
