### ISSUE TITLE
Parameter question

### ISSUE THREAD

**Issue by Huimin721** [kharchenkolab/Baysor#54]
Dear team,

Thank you for the outstanding work! I have a question regarding the parameter. If I do -s 10, and in the toml file, I do:
[Data]
min-molecules-per-gene = 50
min-molecules-per-cell = 8
scale = 14

May I ask, in this case, will Baysor go with 10 or 14?

Best,
Huimin

**Comment by arunchakra** [comment]
the -s 10 will override the config file, as noted in the documentation. You can also see this in the log.

**Comment by VPetukhov** [comment]
Thanks for the response, @arunchakra !
@Huimin721 , indeed, all CLI parameters override config parameters.
