### ISSUE TITLE
Using Known Cell Types from scRNA seq data?

### ISSUE THREAD

**Issue by arunchakra** [kharchenkolab/Baysor#55]
Hello, 

Based on the biorxiv paper, it is suggested that Baysor can use known known cluster definitions from scRNA seq data. I dont see any option to integrate scRNA seq data in the docs though. Is this no longer a possible implementation?

**Comment by VPetukhov** [comment]
Hi,
This kind of functionality is hard to wrap in a CLI. Atm, it's only [available from Julia code](https://github.com/kharchenkolab/BaysorAnalysis/blob/master/notebooks/segmentation_free/segmentation_free_others.md#annotation-transfer). I'm working on wrapping Baysor calls to a [Python package](https://github.com/VPetukhov/baysorpy), but it goes slowly.

So far, Baysor can support arbitrary molecule clustering if you do it with some other package, save it to `cluster` column and then set `--n-clusters=1`. Then, in the logs you'll see something like `Using the following additional information about molecules: [:confidence, :cluster]`, which indicates that it uses provided clusters.

**Comment by SoichiroA** [comment]
Hello, thank you for the great tool!
I was implementing this and saw "Using the following additional information about molecules: [:confidence, :cluster]" in the output file.
Here, some genes are not informative as expressed across cell types. In that case, what should I write in the cluster column for these genes?

Best,
