### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by CristiSoitu** [kharchenkolab/Baysor#56]
Hi, 

First of all, great package!

My issue: If I try to install using the mac binary I get the following message when trying to run the executable:
ERROR: System image file failed consistency check: maybe opened the wrong version?

If I try to install it using CLI, I notice the makefile downloads the linux version of julia and this messes everything up. 

Any ideas how to solve this?

Thanks!

**Comment by carloelle** [comment]
same issue!

**Comment by quentinblampey** [comment]
Is your mac arm64 or x64?
I have the M1 chip and when I tried to install the binary I got the same issue, but I figured out later on that the binary is only for x64

**Comment by Max-Bioinformatics** [comment]
I have an x64 Macbook Pro and I am having this same issue.

**Comment by nhuhoa** [comment]
I have same issue when running binary Mac executable files, MacbookPro, X64

**Comment by VPetukhov** [comment]
Hi,
Sorry, but I gave up building Mac binaries... It's hard to test their reproducibility (requires multiple Mac machines) and the build system is not as polished as Linux. So, for Mac I suggest trying ["Install as a Julia package"](https://github.com/kharchenkolab/Baysor/blob/master/README.md#install-as-a-julia-package), it's greatly simplified in v0.6.0.

**Comment by GBeattie** [comment]
I'm getting same error in Mac M1 despite installing as package:

Used this line for install: 
julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/kharchenkolab/Baysor.git")); Pkg.build()'

Then tried running and got same error:
baysor preview -x x_global_px -y y_global_px --gene target -o ./baysor ./flatFiles_brain/L1_SU500/L1_SU500_tx_file.csv.gz
ERROR: System image file failed consistency check: maybe opened the wrong version?

Will attempt on HPC for now.
