### ISSUE TITLE
Problem with ImageMagick

### ISSUE THREAD

**Issue by asterwardhani** [kharchenkolab/Baysor#6]
I am running this command:
baysor run -i 500 -n 10 -p -c ../../configs/starmap.toml -o ./output_dapi -p ./data/molecules.csv ./data/segmentation.tiff

using the docker container. But it stopped and wanting ImageMagick:
Fatal error:
[17:05:20] Error: ArgumentError("Package ImageMagick not found in current path:\n- Run `import Pkg; Pkg.add(\"ImageMagick\")` to install the ImageMagick package.\n")
|
|                 handle_error(::ArgumentError, ::FileIO.File{FileIO.DataFormat{:TIFF}}) at error_handling.jl:82
|                 handle_exceptions(::Array{Any,1}, ::String) at error_handling.jl:77
|                 load(::FileIO.Formatted; options::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at loadsave.jl:189
|                 load at loadsave.jl:169 [inlined]
|                 #load#13 at loadsave.jl:118 [inlined]
|                 load at loadsave.jl:118 [inlined]
|                 load_centers(::String; min_segment_size::Int64, kwargs::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol,Symbol},NamedTuple{(:x_col, :y_col),Tuple{Symbol,Symbo
l}}}) at CenterData.jl:62
|                 (::Baysor.var"#load_centers##kw")(::NamedTuple{(:x_col, :y_col, :min_segment_size),Tuple{Symbol,Symbol,Int64}}, ::typeof(Baysor.load_centers), ::String) at Ce
nterData.jl:54

**Comment by VPetukhov** [comment]
Thank you for reporting this! There were two issues: first, DockerHub didn't rebuild the docker for quite long, and second, the ImageMagick dependency was implicit, and thus missing in the docker. I fixed the first problem yesterday (https://github.com/kharchenkolab/Baysor/commit/5e5d1f3171d0b8e2acc45a03c014e665c2b73c38), and the latest commit (https://github.com/kharchenkolab/Baysor/commit/775c52cf1e267fc2c3de0f0996ed1ab88e36cdd5) should hopefully fix the second issue. I'll test it today or tomorrow, and if it works, will make a patch release. Then the docker should work fine.

**Comment by asterwardhani** [comment]
cool..I'll give it ago once that's done. Thanks!

Aster.

**Comment by VPetukhov** [comment]
Alright, the version 0.4.1 is there. Please, try `vpetukhov/baysor:master`.

**Comment by asterwardhani** [comment]
Hi Victor,

when I typed baysor inside the container now I get "ERROR: Unable to find
compatible target in system image".

Aster.
