### ISSUE TITLE
Error running with --save-polygons=geojson

### ISSUE THREAD

**Issue by fpestana-git** [kharchenkolab/Baysor#60]
Hi!
Great tool!

I have been trying to extract the polygon information but the --save-polygons=geojson always return an error.

`baysor run -s 50 --scale-std 300 -x x -y y -z z -g gene --min-molecules-per-cell 10 -i 500 --n-clusters 7 -p --save-polygons=geojson -o /tmp/ /tmp/B2_A2_3_test.csv`

```bash
Error: MethodError(Matrix{var"#s597"} where var"#s597"<:Unsigned, (Matrix{Int64}(undef, 0, 0),), 0x00000000000074bd)
|                 
|                 convert(#unused#::Type{Matrix{var"#s597"} where var"#s597"<:Unsigned}, a::Matrix{Int64}) at array.jl:532

```

Not sure what I might be doing wrong.

**Comment by munizmom** [comment]
Hi, I also have the same error running Baysor 0.5.2 from a MacOS M1 env, still it doesn't affect to get the segmentation results. The error appears just after estimating the boundaries.
[16:51:45] Info: Estimating boundary polygons
[16:56:48] Error: MethodError(Matrix{<:Unsigned}, (Matrix{Int64}(undef, 0, 0),), 0x0000000000007fd4)
|                 convert(#unused#::Type{Matrix{<:Unsigned}}, a::Matrix{Int64}) at sys.dylib:?
|                 find_grid_point_labels_kde(pos_data::Matrix{Float64}, cell_labels::Vector{Int64},
min_x::Vector{Float64}, max_x::Vector{Float64}; grid_step::Float64, bandwidth::Float64, dens_threshold::Float64,
min_molecules_per_cell::Int64, verbose::Bool) at sys.dylib:?
|                 (::Baysor.var"#find_grid_point_labels_kde##kw")(::NamedTuple{(:grid_step, :bandwidth), Tuple{Float64,
Float64}}, ::typeof(Baysor.find_grid_point_labels_kde), pos_data::Matrix{Float64}, cell_labels::Vector{Int64},
min_x::Vector{Float64}, max_x::Vector{Float64}) at boundary_estimation.jl:156
|                 boundary_polygons(pos_data::Matrix{Float64}, cell_labels::Vector{Int64}; min_x::Nothing,
max_x::Nothing, grid_step::Float64, min_border_length::Int64, shape_method::Symbol, max_dev::Float64, bandwidth::Float64,
exclude_labels::Vector{Int64}, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}) at sys.dylib:?
|                 boundary_polygons at boundary_estimation.jl:251 [inlined]
|                 #boundary_polygons#218 at boundary_estimation.jl:248 [inlined]
|                 (::Baysor.var"#boundary_polygons##kw")(::NamedTuple{(:grid_step, :bandwidth), Tuple{Float64, Float64}},
::typeof(Baysor.boundary_polygons), spatial_df::DataFrames.DataFrame, args::Vector{Int64}) at boundary_estimation.jl:248
|                 (::Baysor.var"#337#341"{DataFrames.DataFrame, Vector{Int64}, Dict{String, Any},
Float64})(mask::BitVector) at main.jl:220
|                 (::ProgressMeter.var"#56#59"{Distributed.RemoteChannel{Channel{Bool}},
Baysor.var"#337#341"{DataFrames.DataFrame, Vector{Int64}, Dict{String, Any}, Float64}})(x::BitVector) at
ProgressMeter.jl:1018
|                 iterate at generator.jl:47 [inlined]
|                 _collect(c::Vector{BitVector}, itr::Base.Generator{Vector{BitVector},
ProgressMeter.var"#56#59"{Distributed.RemoteChannel{Channel{Bool}}, Baysor.var"#337#341"{DataFrames.DataFrame,
Vector{Int64}, Dict{String, Any}, Float64}}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1}) at array.jl:807
|                 collect_similar(cont::Vector{BitVector}, itr::Base.Generator{Vector{BitVector},
ProgressMeter.var"#56#59"{Distributed.RemoteChannel{Channel{Bool}}, Baysor.var"#337#341"{DataFrames.DataFrame,
Vector{Int64}, Dict{String, Any}, Float64}}}) at array.jl:716
|                 map(f::Function, A::Vector{BitVector}) at abstractarray.jl:2933
|                 macro expansion at ProgressMeter.jl:1017 [inlined]
|                 macro expansion at task.jl:454 [inlined]
|                 macro expansion at ProgressMeter.jl:1016 [inlined]
|                 macro expansion at task.jl:454 [inlined]
|                 progress_map(::Function, ::Vararg{Any}; mapfun::typeof(map), progress::ProgressMeter.Progress,
channel_bufflen::Int64, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}) at ProgressMeter.jl:1009
|                 progress_map(::Function, ::Vararg{Any}) at ProgressMeter.jl:1001
|                 plot_transcript_assignment_panel(df_res::DataFrames.DataFrame, assignment::Vector{Int64},
args::Dict{String, Any}; clusters::Vector{Int64}, prior_polygons::Vector{Matrix{Float64}},
gene_colors::Vector{ColorTypes.Lab{Float64}}) at main.jl:220
|                 (::Baysor.var"#plot_transcript_assignment_panel##kw")(::NamedTuple{(:clusters, :prior_polygons,
:gene_colors), Tuple{Vector{Int64}, Vector{Matrix{Float64}}, Vector{ColorTypes.Lab{Float64}}}},
::typeof(Baysor.plot_transcript_assignment_panel), df_res::DataFrames.DataFrame, assignment::Vector{Int64},
args::Dict{String, Any}) at main.jl:203
|                 save_segmentation_results(bm_data::Baysor.BmmData{3}, gene_names::Vector{String}, args::Dict{String,
Any}; mol_clusts::NamedTuple{(:exprs, :assignment, :diffs, :assignment_probs, :change_fracs), Tuple{Matrix{Float64},
Vector{Int64}, Vector{Float64}, Matrix{Float64}, Vector{Float64}}}, comp_segs::Nothing,
prior_polygons::Vector{Matrix{Float64}}) at main.jl:414
|                 (::Baysor.var"#save_segmentation_results##kw")(::NamedTuple{(:mol_clusts, :comp_segs, :prior_polygons),
Tuple{NamedTuple{(:exprs, :assignment, :diffs, :assignment_probs, :change_fracs), Tuple{Matrix{Float64}, Vector{Int64},
Vector{Float64}, Matrix{Float64}, Vector{Float64}}}, Nothing, Vector{Matrix{Float64}}}},
::typeof(Baysor.save_segmentation_results), bm_data::Baysor.BmmData{3}, gene_names::Vector{String}, args::Dict{String,
Any}) at main.jl:392
|                 run_cli_main(args::Vector{String}) at sys.dylib:?
|                 run_cli(args::Vector{String}) at sys.dylib:?
|                 julia_main() at sys.dylib:?
|                 top-level scope at none:1
└ Baysor /Users/munizmom/Downloads/Baysor-master/src/cli/common.jl:170

**Comment by VPetukhov** [comment]
Hi, I changed the polygon estimation method, so it shouldn't be a problem in v0.6.0. Could you please try it?
