### ISSUE TITLE
Issue with ubuntu version 0.6.0 — 2023-04-20

### ISSUE THREAD

**Issue by nhuhoa** [kharchenkolab/Baysor#69]
Dear Viktor Petukhov,
Thanks for package, this is great work. I tried this latest package, 20-04-2023 that you have uploaded, under my ubuntu 20.04 and there is an issue with input key "InvalidKeyError: invalid key Plotting, possible keys are: data, segmentation, plotting". Is this because of your new change with plotting parameters? Can you help to check this issue?

Noted: I have tested other ubuntu binary versions in release as well but only version 20-04-2023 seems work in my computer. 
Thanks a lot, 

./baysor/bin/baysor run -c ./configs/starmap.toml ./testing/data/molecules.csv ./testing/data/segmentation.tiff
./baysor/bin/baysor run ./testing/pciSeq_data/pciSeq_3-3.csv -c ./configs/iss.toml -o ./testing/pciSeq_output_no_dapi

**ERROR: InvalidKeyError: invalid key Plotting, possible keys are: data, segmentation, plotting**
Stacktrace:
 [1] assert_field_match_exactly(#unused#::Type{Baysor.Utils.RunOptions}, d::Dict{String, Any})
   @ Configurations /home/viktor_petukhov/.julia/packages/Configurations/uH65h/src/from_dict.jl:88
 [2] #from_dict#4
   @ /home/viktor_petukhov/.julia/packages/Configurations/uH65h/src/from_dict.jl:40 [inlined]
 [3] from_dict(::Type{Baysor.Utils.RunOptions}, d::Dict{String, Any})
   @ Configurations /home/viktor_petukhov/.julia/packages/Configurations/uH65h/src/from_dict.jl:33
 [4] command_main(ARGS::Vector{String})
   @ Baysor.CommandLine /home/viktor_petukhov/.julia/packages/Comonicon/rMXvw/src/codegen/julia.jl:278
 [5] command_main
   @ /home/viktor_petukhov/.julia/packages/Comonicon/rMXvw/src/codegen/julia.jl:90 [inlined]
 [6] julia_main()
   @ Baysor.CommandLine /home/viktor_petukhov/.julia/packages/Comonicon/rMXvw/src/frontend/cast.jl:481
 [7] julia_main(; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Baysor /home/viktor_petukhov/.julia/dev/Baysor/src/Baysor.jl:42
 [8] julia_main()
   @ Baysor /home/viktor_petukhov/.julia/dev/Baysor/src/Baysor.jl:42
 [9] top-level scope
   @ none:1

**Comment by nhuhoa** [comment]
Hi all, 

I figured out the issue with the above bug. I used very old config files - incorrect syntax, ex: [Plotting] instead of [plotting] in the latest version. So my new config files example are as in the attachment, and it works. 
Thanks, 
Best, 
Hana

**Comment by VPetukhov** [comment]
Glad to know it works!
