### ISSUE TITLE
Error after pulling the latest Docker container

### ISSUE THREAD

**Issue by asterwardhani** [kharchenkolab/Baysor#7]
After pulling latest, when i typed in Baysor it gives me this error:
"ERROR: Unable to find compatible target in system image."

**Comment by VPetukhov** [comment]
Hm, right, there is a [problem](https://discourse.julialang.org/t/sysimage-incompatible-between-intel-and-amd-x86-64/42716/2) with target CPU architecture for pre-compiled julia binaries, which can't be detected on local tests. I'm working on this.

**Comment by VPetukhov** [comment]
@asterwardhani , I tried to fix it. Can you please test the latest version?
```
docker pull vpetukhov/baysor:master
```

**Comment by asterwardhani** [comment]
> @asterwardhani , I tried to fix it. Can you please test the latest version?
> 
> ```
> docker pull vpetukhov/baysor:master
> ```

Looks like it is working now..thanks!!
