### ISSUE TITLE
Error: DomainError(NaN, "Normal: the condition σ >= zero(σ) is not satisfied.")

### ISSUE THREAD

**Issue by ccbvib** [kharchenkolab/Baysor#74]
I am testing the Baysor run function using Stereoseq data which has been downsampled to the size of the OSM Fish example. This file [test_gem.txt](https://github.com/kharchenkolab/Baysor/files/11435794/test_gem.txt) is the first 20 rows of the downsampled data that I am submitting to Baysor. For whatever reason, I encounter the following error and Baysor run crashes:

 Error: DomainError(NaN, "Normal: the condition σ >= zero(σ) is not satisfied.")|                 
|                 #360 at normal.jl:37 [inlined]
|                 check_args at utils.jl:89 [inlined]
|                 #Normal#359 at normal.jl:37 [inlined]
|                 Normal at normal.jl:37 [inlined]
|                 (::Baysor.var"#129#130"{Vector{Int64}, Vector{Float64}, Matrix{Float64}})(i::Int64) at none:0
|                 iterate at generator.jl:47 [inlined]
|                 indexed_iterate at tuple.jl:92 [inlined]
|                 fit_noise_probabilities(edge_lengths::Vector{Float64}, adjacent_points::Vector{Vector{Int64}}, adjacent_weights::Vector{Vector{Float64}}; m
in_confidence::Nothing, max_iters::Int64, tol::Float64, verbose::Bool, progress::Nothing) at noise_estimation.jl:59
|                 fit_noise_probabilities at noise_estimation.jl:38 [inlined]
|                 append_confidence!(df_spatial::DataFrames.DataFrame, prior_assignment::Nothing; nn_id::Int64, prior_confidence::Float64) at noise_estimatio
n.jl:110
|                 (::Baysor.var"#append_confidence!##kw")(::NamedTuple{(:nn_id, :prior_confidence), Tuple{Int64, Float64}}, ::typeof(Baysor.append_confidence
!), df_spatial::DataFrames.DataFrame, prior_assignment::Nothing) at noise_estimation.jl:104
|                 load_and_preprocess_data!(args::Dict{String, Any}) at main.jl:343
|                 run_cli_main(args::Vector{String}) at main.jl:444
|                 run_cli(args::Vector{String}) at common.jl:152
|                 run_cli at common.jl:137 [inlined]
|                 julia_main() at common.jl:177
|                 top-level scope at none:1

<img width="1439" alt="Screenshot 2023-05-09 at 14 35 36" src="https://github.com/kharchenkolab/Baysor/assets/71338837/c4db3fe3-3231-425c-a70a-d5f2151a71af">

**Comment by VPetukhov** [comment]
Hi @ccbvib , isn't Stereo-seq a spot based protocol? How did you get single-molecule data from that? It's a new use case and I'd be very interested in making it work. 
One immediate idea is that your molecules have integer coordinates, so if there are multiple molecules with the same coordinates, they could be assigned to a single cell, and the radius of this cell would be 0.
