### ISSUE TITLE
Running using starmap example does not show any results

### ISSUE THREAD

**Issue by asterwardhani** [kharchenkolab/Baysor#8]
I was pulling the latest docker container and run the baysor segmentation with and without dapi. In both instances the process showed "Killed" at the end and I do not see any results

**Comment by VPetukhov** [comment]
STARmap segmentation takes ~40Gb RAM. Do you have enough? Otherwise, the process would get killed because of the Out Of Memory problem.

**Comment by asterwardhani** [comment]
Hi, I increased the docker memory and the code seems to run much further. It is now stuck at Plot transcript assignment and never terminated. It appears that it is trying to do some drawing. The segmentation.html shows nothing.

**Comment by VPetukhov** [comment]
Hi, it's a [bug](https://github.com/JuliaPlots/Plots.jl/issues/3117) in the Plots.jl package... I tried to switch to the older version of the package in [v0.4.2](https://github.com/kharchenkolab/Baysor/blob/master/CHANGELOG.md#042--2020-11-26), but looks like it didn't help. So, probably, I will need to re-write this part using some other packages.

**Comment by zachreitz** [comment]
@VPetukhov Is there a workaround for the issue with Plots.jl? I'm running into the same problem.

Although just to confirm, this looks like it's only an issue with the final plots and all the other expected outputs have been completed by that point. Is that correct?

**Comment by VPetukhov** [comment]
@zachreitz , I'm not aware of any quick way. Closer to the end of the month I'm going to make a release that fixes it, but it will take some time.

**Comment by VPetukhov** [comment]
FYI, the fix is in dev (https://github.com/kharchenkolab/Baysor/commit/8622bbc922e1fba3d689ffbf17898a21984ff1d0). Though I still want to add more stuff before a release.

**Comment by VPetukhov** [comment]
The changes are now in the v0.4.3! Docker is updated, as well.
