### ISSUE TITLE
Baysor crashes with OutOfMemoryError() when prior segmentation column contains large integers

### ISSUE THREAD

**Issue by pakiessling** [kharchenkolab/Baysor#83]
I verified this behavior in baysor 0.5.2 and 0.6.1

See the attached csv that crashes baysor when prior segmentation is set to cell_id but not when set to a small integers derived from the id in the column baysor_id.

This is an issue as technology like Vizgen's Merscope use large integers as cell id by default.

[baysor_troubleshoot.csv](https://github.com/kharchenkolab/Baysor/files/11826004/baysor_troubleshoot.csv)

**Comment by VPetukhov** [comment]
And now it's released!
