### ISSUE TITLE
Baysor run stuck after 2D coordinates

### ISSUE THREAD

**Issue by markutz556** [kharchenkolab/Baysor#84]
Hi,

I tried to use Baysor on my data and I think it will be very helpful with the analysis.

I'm running it with my mac (16GB memory with an Intel chip) and I'm stuck with the following step. I've been waiting for over 4 hours and I'm not sure if it's still running or there is any issues. 

![Image 2023-7-17 at 17 22](https://github.com/kharchenkolab/Baysor/assets/32141391/847f6d25-579e-4596-b6bc-fa2de85edb42)

I'm using Baysor version 0.6.1 (install as a Julia package). I wonder if my mac is capable of running Baysor with 1 million transcripts (or if it's possible to run with some modifications).

Any ideas would be appreciated.

Thanks,
Mark

**Comment by VPetukhov** [comment]
Hi @markutz556 , 
That seems to be the same problem of incompatibility with julia 1.9, as https://github.com/kharchenkolab/Baysor/issues/78 . Fixed it in the last [`develop` commit](https://github.com/kharchenkolab/Baysor/commit/586d46f7fb8975d904ae529e13efb1586cc4a203). Hopefully, will release it within a week.

**Comment by markutz556** [comment]
Hi @VPetukhov,

Thanks for your response. I found that this can be solved if I used the --no-ncv-estimation flag. I wonder if the result would be very different with --no-ncv-estimation flag compared with the run without this flag. 

And maybe a naive question. What are the major differences between with ncv estimation and without? Thanks.

Best,
Mark

**Comment by VPetukhov** [comment]
@markutz556 , it's all about plotting. Without NCVs you won't get a segmentation plot, and your output won't have `ncv_color` column that could be used for molecule data visualization.

**Comment by VPetukhov** [comment]
@markutz556 , it's all about plotting. Without NCVs you won't get a segmentation plot, and your output won't have `ncv_color` column that could be used for molecule data visualization.

**Comment by VPetukhov** [comment]
The release is ready now, so it should be fixed.
