### ISSUE TITLE
Error installing CLI

### ISSUE THREAD

**Issue by rlittman16** [kharchenkolab/Baysor#9]
Hello,

I'm trying to install the command line interface, and get the following Errors:

I only provided the end of the compilation logs, let me know if you need anything else.

Thanks in advanced!

  [9b87118b] + PackageCompiler v1.2.4
/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/julia-1.5.3//bin/julia -e 'using Pkg; Pkg.build(); using Baysor' && touch /u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia//deps_success
   Building FFTW → `/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia/packages/FFTW/DMUbN/deps/build.log`
   Building GR ──→ `/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia/packages/GR/RlE5Y/deps/build.log`
   Building HDF5 → `/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia/packages/HDF5/d0V7K/deps/build.log`
WARNING: using StatsBase.wmedian in module Baysor conflicts with an existing identifier.
WARNING: using StatsBase.wmean in module Baysor conflicts with an existing identifier.
/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/julia-1.5.3//bin/julia -e 'using PackageCompiler; import Baysor; create_sysimage(:Baysor; precompile_execution_file="$(dirname(pathof(Baysor)))/../bin/build.jl", replace_default=true)'
ERROR: LoadError: ArgumentError: Package Baysor [cc9f9468-1fbe-11e9-0acf-e9460511877c] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at ./loading.jl:999
 [2] require(::Base.PkgId) at ./loading.jl:928
 [3] require(::Module, ::Symbol) at ./loading.jl:923
 [4] include(::Function, ::Module, ::String) at ./Base.jl:380
 [5] include(::Module, ::String) at ./Base.jl:368
 [6] exec_options(::Base.JLOptions) at ./client.jl:296
 [7] _start() at ./client.jl:506
in expression starting at /u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia/packages/Baysor/KriXT/bin/build.jl:1
ERROR: failed process: Process(`/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/julia-1.5.3/bin/julia --color=yes --startup-file=no --sysimage=/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/julia-1.5.3/lib/julia/sys.so --project=/u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia/environments/v1.5 --compile=all --trace-compile=/tmp/jl_dDxMxX /u/flashscratch/r/rlittman/merfish_scratch/Baysor/bin/.julia/packages/Baysor/KriXT/bin/build.jl`, ProcessExited(1)) [1]

**Comment by rlittman16** [comment]
Any update here?

**Comment by VPetukhov** [comment]
This should be fixed in the develop branch (https://github.com/kharchenkolab/Baysor/commit/4a56c1eaba165f04a12a53796c7f1f9755f741f9). Could you please try installing it from there?

```bash
git clone https://github.com/kharchenkolab/Baysor.git
cd Baysor/bin
git checkout develop
make
```

**Comment by kernco** [comment]
I had the same problem, and switching to the develop branch solved it.

**Comment by cornhundred** [comment]
The make command completed for me after I switched to the develop branch but I do not see any output when running

```
./baysor run --help
```

**Comment by VPetukhov** [comment]
All the changes are now in v0.4.3. Hopefully, should fix the thing.
@cornhundred , could you please try it with the new code? And if it still doesn't work, what's the behavior then? Does it hang or just exit without any message? And what if you run something else, let's say `./baysor blabla`?

**Comment by cornhundred** [comment]
Hi @VPetukhov, I pulled the latest changes 

```
sh-4.2$ git log --oneline
62558d2 (HEAD -> master, origin/master, origin/HEAD) Updated docs
32d88fa Version 0.4.3
``` 

and ran 

```
cd Baysor/bin
make
```

which completed but I am not seeing any output - I included a few lines below:

```
$ baysor run --help
baysor: command not found
$ ./baysor run --help
$ ./baysor blabla
```

However, I can run Baysor from within Julia and see help outputs

```
import Baysor
Baysor.run_cli(["run","--help"])
```

**Comment by VPetukhov** [comment]
Hm, that is totally weird... What distribution do you use (including version)? What happens if you put julia executable in front of `./baysor`? Something like `./julia-1.6.0/bin/julia ./baysor --help` (depends on your installation path)?

> However, I can run Baysor from within Julia and see help outputs

Just to simplify it a bit, you can just pass a full string: `Baysor.run_cli("run --help")`.

**Comment by cornhundred** [comment]
Thanks for your help @VPetukhov. I'm using Julia Version 1.5.3 (2020-11-09)

If I run `<path-to-julia>./julia ./baysor --help` I see the following

```
┌ Warning: Package Plots does not have Dates in its dependencies:
│ - If you have Plots checked out for development and have
│   added Dates as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Plots
└ Loading Dates into Plots from project dependency, future warnings for Plots are suppressed.
```

However, running 

```
<path-to-julia>./julia
julia> import Baysor
julia> Baysor.run_cli("run --help")
```

works.

The baysor file contains 

```
#! <path-to-Baysor>/Baysor/bin/julia-1.5.3//bin/julia\n\nENV["JULIA_DEPOT_PATH"]="<path-to-Baysor>/Baysor/bin/.julia/"\nimport Baysor\nBaysor.run_cli()
#! <path-to-Baysor>/Baysor/bin/julia-1.6.0//bin/julia\n\nENV["JULIA_DEPOT_PATH"]="<path-to-Baysor>/Baysor/bin/.julia/"\nimport Baysor\nBaysor.run_cli()
```

**Comment by VPetukhov** [comment]
> The baysor file contains

That looks like the problem! Somehow, it didn't parse "\n" as the end-of-line symbol. Could you please replace it to get something like the code below?

```
<path-to-Baysor>/Baysor/bin/julia-1.5.3//bin/julia

ENV["JULIA_DEPOT_PATH"]="<path-to-Baysor>/Baysor/bin/.julia/"
import Baysor\nBaysor.run_cli()
```

What OS do you use? I need to check if `echo` behaves differently on it...

**Comment by cornhundred** [comment]
Thanks, @VPetukhov that worked @VPetukhov it looks like the newline parsing was the problem. I am running Amazon Sagemaker 

My output from `$ cat /etc/os-release` is 

```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
```

Although I'm having an issue upgrading to the latest 0.4.3 release, but I can raise that in a different issue (I'm also trying to install on my MacOS).

**Comment by VPetukhov** [comment]
@cornhundred , I replaced `echo` with `printf` (https://github.com/kharchenkolab/Baysor/commit/972081064be6cd90d8422043cd3c7ddf60cbec32), which should behave consistently across different distributions.
