### ISSUE TITLE
Baysor GeoJson output format question

### ISSUE THREAD

**Issue by PoolLab** [kharchenkolab/Baysor#94]
We are trying to integrate Baysor cell segmentation with Merscope downstream analysis tools but we are struggling to get the Baysor output geojson to work with the next steps. It looks like we need to get the data converted to qupath geojson. Would you happen to know which particular geojson format is Baysor putting out so we could figure out which conversions to make?

Thank you in advance!

**Comment by VPetukhov** [comment]
The new Baysor version (v0.7.0) is compatible with the 10x format. Please, see the [discussion here](https://github.com/kharchenkolab/Baysor/issues/129).
